### ISSUE TITLE
Grammatical errors/typo in Readme

### ISSUE THREAD

**Issue by dereko140** [eddiejaoude/book-open-source-tips#105]
1. The following DOs and DON'Ts aim to address some of those basic questions, and offers some pointers to aspiring Open Source developers.

"and offers", shouldn't that be "and offer"?

2. Or, "How do I choose between so many competing projects?”.

There shouldn't be a period at the end of this sentence, similar to the sentence just before.

Thanks.

**Comment by eddiejaoude** [comment]
Yep, good points 👍 . Thank you for pointing them out 🤓 . Do you want to make the changes or are you happy for someone else to?

**Comment by dereko140** [comment]
I'll let someone else have fun this time.

Thanks

**Comment by eddiejaoude** [comment]
Sure 👍
