### ISSUE TITLE
Update README with Filipino translation status

### ISSUE THREAD

**Issue by Vyvy-vi** [eddiejaoude/book-open-source-tips#118]
| Type | Bug |
| :--- | :--- |
| Screenshot included? | yes |
| Description | The current README for the project seems outdated. |

The current table:
![Screenshot 2021-01-21 at 4 05 55 PM](https://user-images.githubusercontent.com/62864373/105339360-971ecc00-5c02-11eb-9f8c-571bc638cf10.png)

Proposed updated table:
| Language | Status | Link |
| :--- | :--- | :--- |
| English | Complete | https://eddiejaoude.github.io/book-open-source-tips/ |
| Spanish | In Progress | https://eddiejaoude.github.io/book-open-source-tips/index-es.html |
| Filipino | In Progress | https://eddiejaoude.github.io/book-open-source-tips/index-fil.html |

**Comment by eddiejaoude** [comment]
Thank you 👍

**Comment by eddiejaoude** [comment]
Merged 👍
