### ISSUE TITLE
Spanish translation update

### ISSUE THREAD

**Issue by JorgePiaggio** [eddiejaoude/book-open-source-tips#119]
| Type | Question |
| :--- | :--- |
| Screenshot included? | no |
| Description | Hi Eddie... a few days ago a PR #117 was accepted with some files translated to spanish, but I can't see them reflected in the [Spanish](https://eddiejaoude.github.io/book-open-source-tips/index-es.html) link. I wanted to take an overview and check if I missed something. Is this an error or am I missing a step? Thanks |

**Comment by eddiejaoude** [comment]
Oh interesting, you are right 🤔 . It could have been a deployment issue, let me check. Thank you for noticing 👍

**Comment by eddiejaoude** [comment]
It was a deployment error, I think I have fixed it now. Please double check 🤓

**Comment by JorgePiaggio** [comment]
DOs are ok now, but DONTs are still in English.

**Comment by eddiejaoude** [comment]
Oh you are right, good spot 👍 . I think I have fixed thank "include" now. Hopefully now it is better?

**Comment by JorgePiaggio** [comment]
Yes, it's fixed now. Thanks Eddie, it's great to somehow have contributed to your book.

Only the appendix needs translation now and the spanish version will be complete. I'd like to leave that task to another contributor willing to help. 

🤓

**Comment by eddiejaoude** [comment]
Thank you again for the contribution 👍
