### ISSUE TITLE
Reasons for not doing god commits

### ISSUE THREAD

**Issue by ImranVirani** [eddiejaoude/book-open-source-tips#122]
Idea
In dont.god-commit.adoc could specific reasons be added to explain why they are bad? I think it would help explain them better.
Screenshot included: no

**Comment by eddiejaoude** [comment]
Thank you for the suggestion, I have made some improvements https://github.com/eddiejaoude/book-open-source-tips/commit/b68e020192927d494dea40c84b34b99ac3c8e517
