### ISSUE TITLE
Duplicated caption in Spanish translation

### ISSUE THREAD

**Issue by GaryHilares** [eddiejaoude/book-open-source-tips#125]
| Type | Bug |
| :--- | :--- |
| Screenshot included? | Yes |
| Description | In the Spanish translation, the caption of the "contribution file" section is duplicated. |

![image](https://user-images.githubusercontent.com/46727048/145684402-3a0f1617-cc9c-4eeb-8a67-b47cd85d0df3.png)
Screenshot (Arrow added by me for clarification).

**Comment by eddiejaoude** [comment]
PR merged
