### ISSUE TITLE
Explain what specific terms are, such as TTD, CVDD, "God commit" and "God pull request" as not everyone, such as me, may not necessarily know what it means.

### ISSUE THREAD

**Issue by ghost** [eddiejaoude/book-open-source-tips#28]
Please remove items in the right column: 

| Type | Bug / Idea |
| :--- | :--- |
| Screenshot included? | yes / no |
| Description | ... |

**Comment by eddiejaoude** [comment]
Good idea, may be with examples (e.g. good & bad examples)

**Comment by charlottebrf** [comment]
@eddiejaoude can this be closed now? Or do you want to put on some good & bad examples of real life projects?

**Comment by eddiejaoude** [comment]
I think this has been half done. Thank you for prompting me. I will create tasks for each to do now and ones I dont do I will create separate Issues for each one:

* [x] TDD
* [x] CVDD
* [ ] ~~Got Commit~~
* [ ] ~~God pull request~~

**Comment by eddiejaoude** [comment]
Added **Appendix** with **Acronyms** [table](https://eddiejaoude.github.io/book-open-source-tips/#_appendix)...

<img width="1018" alt="screenshot 2016-12-04 07 42 47" src="https://cloud.githubusercontent.com/assets/624760/20864795/4db96c9a-b9f5-11e6-866c-b935070b5cfd.png">
