### ISSUE TITLE
Include more beginner information

### ISSUE THREAD

**Issue by StormcastPrime2** [eddiejaoude/book-open-source-tips#32]
Please remove items in the right column: 

| Type Idea |
| Screenshot included? | no |
| Description | I think you should include more information about starting with GitHub such as contributing and working with someone. The information already on there contains lots of strange terms that puzzle beginners. |

**Comment by eddiejaoude** [comment]
May be something like a glossary of **terms**?

For example:

| Term | Meaning |
| :-- | :-- |
| TDD | Test Driven Development |
| CI | Continuous Integration |

**Comment by StormcastPrime2** [comment]
Yes and maybe also a description of what they mean.

**Comment by eddiejaoude** [comment]
Great idea 👍 

| Term | Meaning | Description |
| :-- | :-- | :-- |
| TDD | Test Driven Development | ... |
| CI | Continuous Integration | ... |

**Comment by StormcastPrime2** [comment]
Yes I think that would make it helpful to both experienced coders and beginners

**Comment by eddiejaoude** [comment]
Terms added to [Appendix](https://eddiejaoude.github.io/book-open-source-tips/#_appendix)
