### ISSUE TITLE
Resources quote suggestion

### ISSUE THREAD

**Issue by charlottebrf** [eddiejaoude/book-open-source-tips#42]
| Type | Resources quote  |
| :--- | :--- |
| Screenshot included? | / no |
| Description | "It’s okay to not know everything, and take one step at a time to learn something new." [Source](https://medium.freecodecamp.com/a-beginners-very-bumpy-journey-through-the-world-of-open-source-4d108d540b39#.hm4rvsjbb) @eddiejaoude |

**Comment by eddiejaoude** [comment]
👍

**Comment by eddiejaoude** [comment]
Thanks @charlottebrf . I added it...

<img width="1000" alt="screenshot 2017-01-01 09 52 13" src="https://cloud.githubusercontent.com/assets/624760/21580773/0296a4ca-d008-11e6-9461-62ad908e3145.png">

**Comment by charlottebrf** [comment]
Awesome, so pleased! Found it a handy read for newbies looking to contribute to more open source  💯
